version: '2'

services:
  poc:
    image: mbenz-poc
    container_name: mbenzPoc
    ports:
      - "9000:9000"
#    networks: 
#      - mbenz_default
    restart: always
  routing:
    image: mbenz-routing 
    container_name: mbenz-route
    ports:
      - "9999:9999"
#    networks: 
#    - mbenz_default
    depends_on:
    - "poc"
    restart: always
